//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGFDelivery.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGFDelivery.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        internal static string basket_CheckOut {
            get {
                return ResourceManager.GetString("basket_CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        internal static string basket_items {
            get {
                return ResourceManager.GetString("basket_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minmum Order value is.
        /// </summary>
        internal static string basket_MinmumOrdervalueis {
            get {
                return ResourceManager.GetString("basket_MinmumOrdervalueis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on a delivery order..
        /// </summary>
        internal static string basket_onadeliveryorder {
            get {
                return ResourceManager.GetString("basket_onadeliveryorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have.
        /// </summary>
        internal static string basket_Youhave {
            get {
                return ResourceManager.GetString("basket_Youhave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address *.
        /// </summary>
        internal static string checkout_Address {
            get {
                return ResourceManager.GetString("checkout_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        internal static string checkout_Card {
            get {
                return ResourceManager.GetString("checkout_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string checkout_Cash {
            get {
                return ResourceManager.GetString("checkout_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string checkout_Change {
            get {
                return ResourceManager.GetString("checkout_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number *.
        /// </summary>
        internal static string checkout_ContactNumber {
            get {
                return ResourceManager.GetString("checkout_ContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name *.
        /// </summary>
        internal static string checkout_FirstName {
            get {
                return ResourceManager.GetString("checkout_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method *.
        /// </summary>
        internal static string checkout_PaymentMethod {
            get {
                return ResourceManager.GetString("checkout_PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLACE ORDER AND PAY.
        /// </summary>
        internal static string checkout_PLACEORDERANDPAY {
            get {
                return ResourceManager.GetString("checkout_PLACEORDERANDPAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        internal static string checkout_Postcode {
            get {
                return ResourceManager.GetString("checkout_Postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By proceeding you agree to the Terms &amp; Conditions and Privacy Policy.
        /// </summary>
        internal static string checkout_Privacy {
            get {
                return ResourceManager.GetString("checkout_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY DATA.
        /// </summary>
        internal static string checkout_Title {
            get {
                return ResourceManager.GetString("checkout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string checkout_Total {
            get {
                return ResourceManager.GetString("checkout_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Fields marked with an asterisk must be filled in to proceed.
        /// </summary>
        internal static string checkout_Warn_Info {
            get {
                return ResourceManager.GetString("checkout_Warn_Info", resourceCulture);
            }
        }
        internal static string customize_Side
        {
            get
            {
                return ResourceManager.GetString("customize_Side", resourceCulture);
            }
        }
        internal static string customize_Vegetarian
        {
            get
            {
                return ResourceManager.GetString("customize_Vegetarian", resourceCulture);
            }
        }
        internal static string customize_HotSpicy
        {
            get
            {
                return ResourceManager.GetString("customize_HotSpicy", resourceCulture);
            }
        }
        internal static string customize_GlutenFree
        {
            get
            {
                return ResourceManager.GetString("customize_GlutenFree", resourceCulture);
            }
        }
        internal static string customize_warningmsg
        {
            get
            {
                return ResourceManager.GetString("customize_warningmsg", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        internal static string Collection {
            get {
                return ResourceManager.GetString("Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD TO BASKET.
        /// </summary>
        internal static string deal_ADDTOBASKET {
            get {
                return ResourceManager.GetString("deal_ADDTOBASKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD TO DEAL.
        /// </summary>
        internal static string deal_ADDTODEAL {
            get {
                return ResourceManager.GetString("deal_ADDTODEAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen Sie Ihre.
        /// </summary>
        internal static string deal_Chooseyour {
            get {
                return ResourceManager.GetString("deal_Chooseyour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string deal_Selected {
            get {
                return ResourceManager.GetString("deal_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE.
        /// </summary>
        internal static string deals_CHOOSE {
            get {
                return ResourceManager.GetString("deals_CHOOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string deals_Closed {
            get {
                return ResourceManager.GetString("deals_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEALS.
        /// </summary>
        internal static string deals_DEALS {
            get {
                return ResourceManager.GetString("deals_DEALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeds.
        /// </summary>
        internal static string deals_Feeds {
            get {
                return ResourceManager.GetString("deals_Feeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        internal static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostCode.
        /// </summary>
        internal static string PostCode {
            get {
                return ResourceManager.GetString("PostCode", resourceCulture);
            }
        }
    }
}
